products: Temporary exclude Google apex to continue compilation.
error: packages/modules/RuntimeI18n/apex/Android.bp:66:1: dependency "art-bootclasspath-fragment" of "i18n-bootclasspath-fragm
ent" missing variant:
  apex:com.android.art
available variants:
  os:android,arch:common
error: packages/modules/RuntimeI18n/apex/Android.bp:66:1: dependency "prebuilt_art-bootclasspath-fragment" of "i18n-bootclassp
ath-fragment" missing variant:
  apex:com.android.art
available variants:
  os:android,arch:common

Signed-off-by: spezi77 <spezi7713@gmx.net>